throw抛异常
制造报错 throw ‘’ 会造成终断
throw new Error ('') 能够抛出更详细的错误信息

try/catch 捕获错误信息
try {
   可能发送错误的代码
} catch(err){
 拦截错误，提示浏览器提供错误信息 但是不中断程序的执行
 console.log(err.message)
return
需要加  return 中断程序
或者搭配 throw使用
}
finally {
不管对不对，一定会执行的代码
}

debugger 手动输入一个断点